// Auto-generated by make — do not edit
let buildVersion = "1.5.5"
let buildCommit = "b33a1b5"
let buildBranch = "main"
let buildDate = "2026-06-09 23:13:15 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
