// Auto-generated by make — do not edit
let buildVersion = "1.6.0"
let buildCommit = "5a0a169"
let buildBranch = "main"
let buildDate = "2026-06-14 22:14:17 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
