// Auto-generated by make — do not edit
let buildVersion = "1.9.1"
let buildCommit = "0e92fc6"
let buildBranch = "main"
let buildDate = "2026-08-05 16:31:21 UTC"
let buildSwiftVersion = "6.3.3"
let buildOS = "macOS 26.5.2"
