// ============================================================================
// Summarizer.swift — Context strategy: compress old history into a summary
// Part of apfel-plus — Apple Intelligence from the command line
//
// Uses the on-device model itself to generate a summary of older turns,
// keeping recent turns verbatim. Falls back to newest-first on failure.
// ============================================================================

import FoundationModels
import Foundation
import ApfelCore

/// A summarizer closure: renders old history text -> an optional summary string.
/// `maxTokens` is the cap the summary should respect when generated by the model.
/// Default is the real on-device `generateSummary`; injectable for deterministic tests.
typealias Summarizer = (_ text: String, _ maxTokens: Int, _ permissive: Bool) async -> String?

/// Fraction of the budget the summary itself is allowed to consume when generated.
private let summaryBudgetFraction = 4   // budget / 4

/// Summarize old history entries, keeping recent ones verbatim.
/// Falls back to newest-first if summarization fails or budget is too tight.
///
/// `summarize` is injectable so a unit test can stub a deliberately-huge summary
/// and assert the assembled transcript is still verified against the budget.
func trimWithSummary(
    base: [Transcript.Entry], history: [Transcript.Entry],
    final: Transcript.Entry?, budget: Int,
    permissive: Bool = false,
    summarize: Summarizer = { text, maxTokens, permissive in
        await generateSummary(text, maxTokens: maxTokens, permissive: permissive)
    }
) async -> [Transcript.Entry] {
    guard history.count > 2 else {
        return await trimNewestFirst(
            base: base, history: history, final: final, budget: budget)
    }

    // Split: keep recent 50% of budget, summarize the rest
    let halfBudget = budget / 2
    let recentCount = await maxNewestHistoryCountThatFits(
        base: base,
        history: history,
        final: final,
        budget: halfBudget
    )
    let recentEntries = Array(history.suffix(recentCount))

    let oldEntries = Array(history.dropLast(recentEntries.count))
    guard !oldEntries.isEmpty else {
        return assembleTranscriptEntries(base: base, history: recentEntries)
    }

    // Render old entries to text for summarization
    let oldText = renderEntries(oldEntries)
    guard !oldText.isEmpty else {
        return await trimNewestFirst(
            base: base, history: history, final: final, budget: budget)
    }

    // Cap the summary to a fraction of the budget so it cannot grow unbounded.
    let summaryMaxTokens = max(1, budget / summaryBudgetFraction)

    // Summarize using the injected summarizer (the on-device model by default).
    let summaryText = await summarize(oldText, summaryMaxTokens, permissive)
    guard let summaryText else {
        return await trimNewestFirst(
            base: base, history: history, final: final, budget: budget)
    }

    let segment = Transcript.TextSegment(content: "[Summary of prior conversation]: \(summaryText)")
    let summaryEntry = Transcript.Entry.response(
        Transcript.Response(assetIDs: [], segments: [.text(segment)]))

    // Even with a bounded summary, verify the assembled transcript actually fits
    // the budget before returning it. A summary the model overshoots, or a tight
    // budget, can still push the total past the limit — fall back to newest-first.
    let summarized = [summaryEntry] + recentEntries
    guard await fitsTranscriptBudget(
        base: base, history: summarized, final: final, budget: budget
    ) else {
        return await trimNewestFirst(
            base: base, history: history, final: final, budget: budget)
    }

    return assembleTranscriptEntries(base: base, history: summarized)
}

// MARK: - Helpers

private func renderEntries(_ entries: [Transcript.Entry]) -> String {
    entries.compactMap { entry -> String? in
        switch entry {
        case .prompt(let p):
            return p.segments.compactMap { seg in
                if case .text(let t) = seg { return "User: \(t.content)" }; return nil
            }.joined()
        case .response(let r):
            return r.segments.compactMap { seg in
                if case .text(let t) = seg { return "Assistant: \(t.content)" }; return nil
            }.joined()
        default: return nil
        }
    }.joined(separator: "\n")
}

private func generateSummary(
    _ text: String, maxTokens: Int, permissive: Bool = false
) async -> String? {
    let model = makeModel(permissive: permissive)
    let session = LanguageModelSession(
        model: model,
        instructions: "Summarize the following conversation in 2-3 sentences. Be concise."
    )
    do {
        // Bound the summary length so it cannot grow unbounded and blow the budget.
        let options = GenerationOptions(maximumResponseTokens: maxTokens)
        let response = try await session.respond(to: text, options: options)
        let summary = response.content.trimmingCharacters(in: .whitespacesAndNewlines)
        return summary.isEmpty ? nil : summary
    } catch {
        return nil
    }
}
