#!/usr/bin/env bash
# generate-demos.sh - embed demo/ into Sources/Core/GeneratedDemos.swift so the
# `apfel-plus demos <dir>` command can write the demo scripts out identically across
# every install method (homebrew-core, tap, source build). Each demo file is
# base64-encoded to sidestep all Swift string-escaping concerns.
#
# Re-run whenever demo/ changes. Tests/integration/test_demos.py asserts the
# generated file stays in sync with demo/.
#
# Usage: ./scripts/generate-demos.sh [demo_dir] [output_file]
set -euo pipefail

demo_dir="${1:-demo}"
out="${2:-Sources/Core/GeneratedDemos.swift}"

[ -d "$demo_dir" ] || { echo "generate-demos: $demo_dir not found" >&2; exit 1; }

tmp=$(mktemp)
{
  echo "// Generated by scripts/generate-demos.sh - DO NOT EDIT."
  echo "//"
  echo "// Embeds demo/ so \`apfel-plus demos <dir>\` can write the demos out, identically"
  echo "// across homebrew-core, the tap, and source builds (the demos travel inside"
  echo "// the binary rather than depending on the install layout)."
  echo ""
  echo "public struct EmbeddedDemo: Sendable, Equatable {"
  echo "    public let name: String"
  echo "    public let isExecutable: Bool"
  echo "    public let base64: String"
  echo "}"
  echo ""
  echo "public let embeddedDemos: [EmbeddedDemo] = ["
  # Deterministic order so the generated file is stable across machines.
  for f in $(find "$demo_dir" -maxdepth 1 -type f | LC_ALL=C sort); do
    name=$(basename "$f")
    if [ -x "$f" ]; then exec_flag="true"; else exec_flag="false"; fi
    b64=$(base64 < "$f" | tr -d '\n')
    echo "    EmbeddedDemo(name: \"$name\", isExecutable: $exec_flag, base64: \"$b64\"),"
  done
  echo "]"
} > "$tmp"

if ! cmp -s "$tmp" "$out"; then
  mv "$tmp" "$out"
  echo "generate-demos: wrote $out"
else
  rm "$tmp"
  echo "generate-demos: $out already up to date"
fi
