#compdef apfel
# apfel(1) zsh completion - generated by `apfel completions zsh`
_apfel() {
  if (( CURRENT == 3 )) && [[ ${words[2]} == completions ]]; then
    _values 'shell' bash zsh fish
    return
  fi
  _arguments -s \
    '-h[Show help]' \
    '--help[Show help]' \
    '-v[Print version]' \
    '--version[Print version]' \
    '--release[Show detailed build info]' \
    '-s[Set a system prompt]:value:' \
    '--system[Set a system prompt]:value:' \
    '--system-file[Read system prompt from file]:file:_files' \
    '-o[Output format]:value:(plain json)' \
    '--output[Output format]:value:(plain json)' \
    '-q[Suppress non-essential output]' \
    '--quiet[Suppress non-essential output]' \
    '--no-color[Disable colored output]' \
    '--chat[Interactive conversation]' \
    '--stream[Stream a single response]' \
    '--serve[Start OpenAI-compatible HTTP server]' \
    '--benchmark[Run internal benchmarks]' \
    '--count-tokens[Count tokens without calling the model]' \
    '--strict[With --count-tokens: exit 4 if over budget]' \
    '--model-info[Print model capabilities]' \
    '--update[Check for updates via Homebrew]' \
    '--demos[Write bundled demo scripts to dir]:dir:_files -/' \
    '--port[Server port]:value:' \
    '--host[Server bind address]:value:' \
    '--cors[Enable CORS headers]' \
    '--max-concurrent[Max concurrent requests]:value:' \
    '--debug[Enable debug logging]' \
    '--allowed-origins[Comma-separated allowed origins]:value:' \
    '--no-origin-check[Disable origin checking]' \
    '--token[Require Bearer token auth]:value:' \
    '--token-auto[Generate a random Bearer token]' \
    '--public-health[Keep /health unauthenticated]' \
    '--footgun[Disable all protections]' \
    '--mcp[Attach local or remote MCP server]:file:_files' \
    '--mcp-timeout[MCP timeout in seconds]:value:' \
    '--mcp-token[Bearer token for remote MCP servers]:value:' \
    '--temperature[Sampling temperature]:value:' \
    '--top-p[Nucleus sampling threshold]:value:' \
    '--seed[Random seed]:value:' \
    '--max-tokens[Maximum response tokens]:value:' \
    '--permissive[Use permissive guardrails]' \
    '--retry[Enable retry with backoff]' \
    '--context-strategy[Context management strategy]:value:(newest-first oldest-first sliding-window summarize strict)' \
    '--context-max-turns[Max history turns]:value:' \
    '--context-output-reserve[Tokens reserved for output]:value:' \
    '--context-status[Print context fill after each turn]' \
    '-f[Attach file content to prompt]:file:_files' \
    '--file[Attach file content to prompt]:file:_files' \
    '--schema[Constrain output to a JSON Schema file]:file:_files' \
    '--messages[One-shot multi-turn from OpenAI messages JSON]:file:_files' \
    '--code[Print only the first fenced code block of the response]' \
    '1:command:(completions)' \
    '*:file:_files'
}
_apfel "$@"
