# apfel(1) bash completion - generated by `apfel completions bash`
_apfel() {
    local cur prev
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # `apfel completions <shell>` subcommand
    if [ "${COMP_WORDS[1]}" = "completions" ] && [ "$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") ); return 0
    fi

    case "$prev" in
        -o|--output)
            COMPREPLY=( $(compgen -W "plain json" -- "$cur") ); return 0 ;;
        --context-strategy)
            COMPREPLY=( $(compgen -W "newest-first oldest-first sliding-window summarize strict" -- "$cur") ); return 0 ;;
        --system-file|--mcp|-f|--file|--schema|--messages)
            COMPREPLY=( $(compgen -f -- "$cur") ); return 0 ;;
        --demos)
            COMPREPLY=( $(compgen -d -- "$cur") ); return 0 ;;
        -s|--system|--port|--host|--max-concurrent|--allowed-origins|--token|--mcp-timeout|--mcp-token|--temperature|--top-p|--seed|--max-tokens|--context-max-turns|--context-output-reserve)
            return 0 ;;
    esac

    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "--allowed-origins --benchmark --chat --code --context-max-turns --context-output-reserve --context-status --context-strategy --cors --count-tokens --debug --demos --file --footgun --help --host --max-concurrent --max-tokens --mcp --mcp-timeout --mcp-token --messages --model-info --no-color --no-origin-check --output --permissive --port --public-health --quiet --release --retry --schema --seed --serve --stream --strict --system --system-file --temperature --token --token-auto --top-p --update --version -f -h -o -q -s -v completions" -- "$cur") ); return 0
    fi
    COMPREPLY=( $(compgen -f -- "$cur") ); return 0
}
complete -F _apfel apfel
